### ISSUE TITLE
Here is the list of all non working Sources of LNReader

### ISSUE THREAD

**Issue by Pheonix-Flames** [LNReader/lnreader#305] opened 2022-06-18 14:55 UTC
https://github.com/LNReader/lnreader-sources/issues/317#issue-1275663784

ComradeMao
FastNovel
KissLightNovels
LightNovelPub
LightNovelHub
[Ltnovel.com](http://ltnovel.com/)
MTLCornor
NitroScans
Novelmt
NovelPub
NovelsRock
OnlyMTL
Readwn
WebNovelLove
[Wuxia.city](http://wuxia.city/)
[WuxiaWorld.cloud](http://wuxiaworld.cloud/)

**Comment by rajarsheechatterjee** [comment] 2022-06-18 15:09
Duplicate of LNReader/lnreader-sources#317

**Closed by rajarsheechatterjee** 2022-06-18 15:09 UTC
