### ISSUE TITLE
Start TTS from selected paragraph 

### ISSUE THREAD

**Issue by sjain3097** [LNReader/lnreader#533] opened 2023-02-09 08:16 UTC
### Describe your suggested feature

Hi this is a request for a feature.
Allow to start text to speech from the selected paragraph in the novel chapter and autoscroll the chapter as it reads the paragraph to the top of the screen.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/LNReader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.14](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarshee-harness** [comment] 2023-02-09 08:17
Duplicate of #90

**Closed by rajarshee-harness** 2023-02-09 08:17 UTC
Labels: Feature Request
