### ISSUE TITLE
TTS Reading Speed Control

### ISSUE THREAD

**Issue by massXtrash** [LNReader/lnreader#1016] opened 2024-03-27 15:34 UTC
### Describe your suggested feature

If.... Is it possible to add TTS read speed control feature like moon+ reader pro or [T2S](https://play.google.com/store/apps/details?id=hesoft.T2S) ???

### Other details

**Moon+ Reader Pro**
![Screenshot_2024-03-27-21-35-57-018_com flyersoft moonreader](https://github.com/LNReader/lnreader/assets/150979330/07b1210a-8adc-4b8a-bae9-4249665d49eb)

--------
**T2S**
![Screenshot_2024-03-27-21-35-48-582_hesoft T2S](https://github.com/LNReader/lnreader/assets/150979330/8d09dd96-c987-4435-b3a0-97b7d8f745a8)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/LNReader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.19](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment] 2024-03-29 03:11
Duplicate of #90

**Closed by rajarsheechatterjee** 2024-03-29 03:11 UTC
Labels: Feature Request
