### ISSUE TITLE
Add a feature to auto delete chapters after finishing reading the novel

### ISSUE THREAD

**Issue by Pheonix-Flames** [LNReader/lnreader#382] opened 2022-08-15 13:34 UTC
Add a feature to auto delete chapters after finishing reading the novel

For Reference : 
![Screenshot_2022-08-15-19-03-39-27_a603e4da04bada03cae438f177815547](https://user-images.githubusercontent.com/105352597/184645183-8b20cae0-51fd-4024-8c1b-749c3d5d1c77.jpg)
![Screenshot_2022-08-15-19-03-41-38_a603e4da04bada03cae438f177815547](https://user-images.githubusercontent.com/105352597/184645189-c2760cd9-7c6f-4d0c-860a-51d517d2e1ee.jpg)

**Comment by rajarsheechatterjee** [comment] 2022-08-15 15:02
Duplicate of #115

**Closed by rajarsheechatterjee** 2022-08-15 15:02 UTC
