### ISSUE TITLE
Add a new feature

### ISSUE THREAD

**Issue by josephfrances123** [LNReader/lnreader#425] opened 2022-09-04 12:50 UTC
Good day. May I ask if it is possible to add a feature where we can flip pages? Or that we can use volume buttons to go to next page?

It will be a great help I think?

Thank you and have a nice day 🥰

**Comment by rajarsheechatterjee** [comment] 2022-09-13 02:52
> add a feature where we can flip pages

Duplicate of #29

Scrolling using volume buttons is there if you turn Render HTML on in reader settings.

**Closed by rajarsheechatterjee** 2022-09-13 02:52 UTC
