### ISSUE TITLE
Directly Adding option

### ISSUE THREAD

**Issue by Solovertical** [LNReader/lnreader#362] opened 2022-08-12 02:03 UTC
1: On searching source in global
 we should add it directly by long pressing the sources in any category we want . 
It easier to add from here directly 
![Screenshot_2022-08-12-07-09-13-050_com rajarsheechatterjee LNReader](https://user-images.githubusercontent.com/109901807/184271337-2b8aaf12-041c-480f-8d48-1c9518148e26.png)

**Comment by rajarsheechatterjee** [comment] 2022-08-12 15:40
Duplicate of #151

**Closed by rajarsheechatterjee** 2022-08-12 15:40 UTC
Labels: Enhancement
