### ISSUE TITLE
[Feature Request]  Horizontal Reading Mode

### ISSUE THREAD

**Issue by massmia** [LNReader/lnreader#316] opened 2022-07-03 19:41 UTC
Is it possible to add horizontal reading mode option?  I kinda like it.
![Screenshot_20220704-013608_NovelFull.png](https://user-images.githubusercontent.com/98101010/177054918-17492751-6d40-4355-a419-df083bd7c078.png)

**Comment by rajarsheechatterjee** [comment] 2022-07-05 12:04
Duplicate of #29

**Closed by rajarsheechatterjee** 2022-07-05 12:04 UTC
