### ISSUE TITLE
[Feature Request] Add a feature to auto delete chapters after reading

### ISSUE THREAD

**Issue by Pheonix-Flames** [LNReader/lnreader#299] opened 2022-06-14 12:05 UTC
Thete is a option in tachiyomi which delete a chapter after reading it can you add same type of option in LNReader

![Screenshot_2022-06-14-17-34-45-43_a603e4da04bada03cae438f177815547](https://user-images.githubusercontent.com/105352597/173572894-ba0b86f9-5509-43cf-a9d4-807ea09dbe3b.jpg)

**Comment by rajarsheechatterjee** [comment] 2022-06-15 14:11
Duplicate of #115

**Closed by rajarsheechatterjee** 2022-06-15 14:11 UTC
