### ISSUE TITLE
Add mtlarchive site , it has best mtl novels 

### ISSUE THREAD

**Issue by Legendoras** [LNReader/lnreader#1215] opened 2024-08-16 13:11 UTC
### Describe your suggested feature

I am reading novels for now more than 2 years on that site mtlarchive which is before known as mtlnation, so can you please add this site in sources 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/LNReader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[2.0.0](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment] 2024-08-16 14:18
> If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).

>  I have searched the existing issues and this is a new ticket, NOT a duplicate or related to another open or closed issue.

Duplicate of https://github.com/LNReader/lnreader-plugins/issues/941

**Closed by rajarsheechatterjee** 2024-08-16 14:18 UTC
Labels: Feature Request
