### ISSUE TITLE
Double tap to trigger settings 

### ISSUE THREAD

**Issue by Palloxin** [LNReader/lnreader#642] opened 2023-05-29 06:42 UTC
### Describe your suggested feature

https://github.com/LNReader/lnreader/assets/75091899/de51cd0f-13a9-4f77-8ed0-f00930090804

While reading i often accidentally tap on the screen and the setting appear and it is annoying. I would like a double as so that it doesn't happen.

### Other details

The video is from shosetsu

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/LNReader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.14](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment] 2023-07-02 06:04
Duplicate of #229

**Closed by rajarsheechatterjee** 2023-07-02 06:04 UTC
Labels: Feature Request
