### ISSUE TITLE
Feature request  external  Epub support 

### ISSUE THREAD

**Issue by hassan852** [LNReader/lnreader#107] opened 2021-11-16 16:42 UTC
A lot of good translations/official translations are not available on the aggregator sites, and can only be obtained locally, Request local epub support as that would allow readers to access their personal collections within the Thier devices 
And thank u for hard work sir

**Comment by rajarsheechatterjee** [comment] 2021-11-17 03:51
Duplicate of #38

**Closed by rajarsheechatterjee** 2021-11-17 03:51 UTC
