### ISSUE TITLE
[feature request] Send crash reports or a dump crash logs

### ISSUE THREAD

**Issue by Vilianexe** [LNReader/lnreader#191] opened 2022-03-05 15:47 UTC
Sometimes the app crash when i'm in settings, and i wanted to know why, or just help improve the app, sending anonymous crash reports or opening and issue with the crash log, thank you i'm loving the app and wanted to help

**Comment by rajarsheechatterjee** [comment] 2022-03-05 15:54
Duplicate of #11

I don't know how to implement it right now.

**Closed by rajarsheechatterjee** 2022-03-05 15:54 UTC
