### ISSUE TITLE
Make epubs.

### ISSUE THREAD

**Issue by Bones-ishere** [LNReader/lnreader#1328] opened 2024-11-17 21:47 UTC
### Describe your suggested feature

The feature where you can import epubs is so good, but there was an option where you can make epubs from the downloaded chapters from the app please add it back.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/LNReader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[2.0.0](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by CD-Z** [comment] 2024-11-17 22:33
Duplicate of  #1309

**Closed** 2024-11-17 23:42 UTC
Labels: Feature Request
