### ISSUE TITLE
Text to speech system.

### ISSUE THREAD

**Issue by PrincejiCoder** [LNReader/lnreader#1348] opened 2024-12-07 08:46 UTC
### Describe your suggested feature

I Like to hear audio of light novel more then reading. But in ln reader.
There is **no feature** where I just toggle speech button one time and the text to speech system reads the chapter one after another. Without me having to open my phone Every time a chapter end and got to the chapter next in sequence and toggle the speech button again. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/LNReader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[2.0.0](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Awesomoe4000** [comment] 2024-12-20 13:32
I have the same issue and hope there could be a option for listening to 3, 5, or 10 chapters in sequence. I ask for a set amount because I'm sure I'll forget to stop it not sure how many chapters will pass before I notice.

**Comment by rajarsheechatterjee** [comment] 2024-12-24 03:14
Duplicate of #465

**Closed by rajarsheechatterjee** 2024-12-24 03:14 UTC
Labels: Feature Request
