### ISSUE TITLE
When the text has angle brackets (e.g <text>) it becomes invisible.

### ISSUE THREAD

**Issue by SulfurO2** [LNReader/lnreader#1050] opened 2024-04-26 16:34 UTC
### Steps to reproduce

Open "the authors pov"
Example: ch 108
![Screenshot_2024-04-26-21-25-26-44_3c1c179116822eec69c21805387f0489](https://github.com/LNReader/lnreader/assets/118686826/571cb2bd-0e2c-424e-94ae-6a3b189a9f7a)

### Expected behavior

I should be able to see the text:  <B>

### Actual behavior

The text is invisible.
![Screenshot_2024-04-26-21-25-16-21_3c1c179116822eec69c21805387f0489](https://github.com/LNReader/lnreader/assets/118686826/760a6d1f-d48f-4a79-a3cd-67fcb3d93e91)

### LNReader version

2.0.0

### Android version

Android 13

### Device

Oppo Reno 6

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[2.0.0](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment] 2024-04-27 03:32
Duplicate of #1005

**Closed by rajarsheechatterjee** 2024-04-27 03:32 UTC
Labels: Bug
