### ISSUE TITLE
translator feature

### ISSUE THREAD

**Issue by Zizouu2** [LNReader/lnreader#938] opened 2024-02-02 06:23 UTC
### Describe your suggested feature

when will LNReader have a translator feature 
![reader png](https://github.com/LNReader/lnreader/assets/157443292/fb916b4d-b66e-4c40-a7e8-b442f61a4039)

### Acknowledgements

- [ ] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [ ] I have written a short but informative title.
- [ ] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/LNReader/lnreader-sources/issues/new/choose).
- [ ] I have updated the app to version **[1.1.19](https://github.com/LNReader/lnreader/releases/latest)**.
- [ ] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment] 2024-02-02 15:42
Duplicate of #439

**Closed by rajarsheechatterjee** 2024-02-02 15:42 UTC
Labels: Feature Request
