### ISSUE TITLE
Notes and highlights

### ISSUE THREAD

**Issue by 00p11** [LNReader/lnreader#894] opened 2024-01-11 18:13 UTC
### Describe your suggested feature

It would be great if the app had feature to add notes and highlight like this:
![Highlight-Toolbar-Kindle-Paperwhite](https://github.com/LNReader/lnreader/assets/97852460/5f162731-c01e-4fdf-9804-62b687ba25b4)
Thanks!

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [x] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/LNReader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.18](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Palloxin** [comment] 2024-08-20 13:30
Seems a duplicate of #524 (I suggest to an admin to change the title of the issue 524)

**Closed** 2024-08-21 03:25 UTC
Labels: Feature Request
