### ISSUE TITLE
Mtlnation source request.

### ISSUE THREAD

**Issue by Adrianjack** [LNReader/lnreader#948] opened 2024-02-12 16:12 UTC
### Describe your suggested feature

Adding mtlnation to the app.

### Other details

Mtlnation is a great website with very frequent updates.
It would be great if login to account was possible as mtlnation allows guest account to read only up to 100 chapters. Afterwards the chapters are incomplete.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/LNReader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.19](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Adrianjack** [comment] 2024-02-12 16:12
If Mtlnation is added I'm switching permanently to this app instead of using crawlers and brave.

**Comment by rajarsheechatterjee** [comment] 2024-02-12 16:13
> If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).

Duplicate of https://github.com/LNReader/lnreader-sources/issues/81

**Closed by rajarsheechatterjee** 2024-02-12 16:13 UTC
Labels: Feature Request

**Comment by Adrianjack** [comment] 2024-02-12 16:20
Can you tell why you can't add mtlnation.

**Comment by rajarsheechatterjee** [comment] 2024-02-12 16:25
It's an open source app. You can either wait for someone to add it or feel free to contribute and add it yourself.
