### ISSUE TITLE
Add infinite scrolling  for tts 

### ISSUE THREAD

**Issue by Legendoras** [LNReader/lnreader#1214] opened 2024-08-16 13:10 UTC
### Describe your suggested feature

I am tired of manually changing chapter and then turn on tts again and again , can you please add feature so the tts will not stop and reading chapters continuously 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/LNReader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[2.0.0](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment] 2024-08-17 09:54
Duplicate of #759

**Closed by rajarsheechatterjee** 2024-08-17 09:54 UTC
Labels: Feature Request
