### ISSUE TITLE
extension not working Ranobes

### ISSUE THREAD

**Issue by MM001-r** [LNReader/lnreader#517] opened 2023-01-23 07:56 UTC
### Steps to reproduce

when launching the extension, a black screen with an inscription 

### Expected behavior

work in standard mode 

### Actual behavior

Does not work

### LNReader version

1.1.13

### Android version

Android 13

### Device

OnePlus 9 rt

### Other details

Hello guys, this is the problem, everything is loaded through the site, but not through the application ...
![Screenshot_2023-01-23-10-44-13-13_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/71752683/213989921-f8db3a5e-1983-4755-a251-e25b6cae6af8.jpg)
![Screenshot_2023-01-23-10-55-19-62_3c1c179116822eec69c21805387f0489](https://user-images.githubusercontent.com/71752683/213989926-dbc6fb55-0290-465b-a154-a327f2502244.jpg)
![Screenshot_2023-01-23-10-55-22-35_3c1c179116822eec69c21805387f0489](https://user-images.githubusercontent.com/71752683/213989934-d22c0fbe-74ce-4fd6-84ea-d377ca93dd64.jpg)
![Screenshot_2023-01-23-10-55-32-99_3c1c179116822eec69c21805387f0489](https://user-images.githubusercontent.com/71752683/213989935-3d6e826e-4046-4075-b30c-209c8eb4774f.jpg)
![Screenshot_2023-01-23-10-55-37-83_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/71752683/213989938-4eeda980-ded5-4fbb-a992-3a0eb4dd57fd.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.13](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment] 2023-01-23 08:02
> If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).

Duplicate of LNReader/lnreader-sources#435

**Closed by rajarsheechatterjee** 2023-01-23 08:02 UTC
Labels: Bug
