### ISSUE TITLE
Translator chapters

### ISSUE THREAD

**Issue by AtreussOT** [LNReader/lnreader#556] opened 2023-02-19 01:29 UTC
### Describe your suggested feature

I would like the application to have the option to translate the chapters, without having to go to the web view option to translate it

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/LNReader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.14](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment] 2023-02-19 02:41
Duplicate of #439

**Closed by rajarsheechatterjee** 2023-02-19 02:41 UTC
Labels: Feature Request
