### ISSUE TITLE
LNReader library restoration

### ISSUE THREAD

**Issue by LienneTan** [LNReader/lnreader#901] opened 2024-01-18 10:45 UTC
![Screenshot_20240118-184130](https://github.com/LNReader/lnreader/assets/157014066/b6455c1c-4c11-4e7a-baf5-8bb8cb5b82cd)
Hello. I recently changed my phone so I wanted to read the novels I added in my library from the other phone. I tried to make a back up on my previous phone, then uploaded it somewhere for me to retrieve. However, when I downloaded the file, this error (picture above) is showing up. What should I do?

**Comment by rajarsheechatterjee** [comment] 2024-01-20 11:01
Duplicate of #633

**Closed by rajarsheechatterjee** 2024-01-20 11:01 UTC
