### ISSUE TITLE
Add Categories.

### ISSUE THREAD

**Issue by MazenMohamed909** [LNReader/lnreader#260] opened 2022-05-13 02:10 UTC
Heyo, I want to thank you for your hard work on this app, I like it very much and if without it I don't think I can survive for long on the novels sites.
I just recommend having a categories option like tachiyomi app to add some novels for next to read, finished, etc. And thanks.

**Comment by rajarsheechatterjee** [comment] 2022-05-19 11:44
Duplicate of #45

**Closed by rajarsheechatterjee** 2022-05-19 11:44 UTC
