### ISSUE TITLE
More Features in TTS

### ISSUE THREAD

**Issue by Azrox01** [LNReader/lnreader#932] opened 2024-01-30 14:30 UTC
### Describe your suggested feature

Make it automatically change chapters and start reading the next chapter while in TTS mode, and highlight what paragraph it is reading. and give virtual buttons to move between paragraphs.

### Other details

its just annoying to click next chapter every time while listening to a novel, and it will be very helpful to change to previous or next paragraphs while listening.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/LNReader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.19](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment] 2024-01-31 16:45
Duplicate of #90

**Closed by rajarsheechatterjee** 2024-01-31 16:45 UTC
Labels: Feature Request
