### ISSUE TITLE
Scheduled Library Updates

### ISSUE THREAD

**Issue by Batorian** [LNReader/lnreader#1208] opened 2024-08-12 22:39 UTC
### Describe your suggested feature

- user should be able to schedule library updates (every 6h, every 12h, etc.)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/LNReader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[2.0.0](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Palloxin** [comment] 2024-08-12 22:40
The rate of plugins breaking will increse if u let users choose

**Comment by Batorian** [comment] 2024-08-12 22:49
> The rate of plugins breaking will increse if u let users choose

I don't understand what you mean. All I want is the option to have the library updated periodically instead of app start. It shouldn't interfere with any plugins.

**Comment by Palloxin** [comment] 2024-08-20 12:44
Duplicate of #13

**Closed** 2024-08-21 03:24 UTC
Labels: Feature Request
