### ISSUE TITLE
Discord server 

### ISSUE THREAD

**Issue by SuperDuperNoob** [LNReader/lnreader#971] opened 2024-02-24 20:24 UTC
### Steps to reproduce

1.open app 2.click discord logo 3.cant join because link expired

### Expected behavior

It should let us join lnreader discord server 

### Actual behavior

But the link is expired instead 

### LNReader version

1.1.19

### Android version

Android 8

### Device

HTC U11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.19](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by edmxn** [comment] 2024-03-16 20:37
It works to me
discord.gg/QdcWN4MD63

**Comment by sengjung123** [comment] 2024-03-22 22:30
Have you tried ensuring that your total discord servers joined is <100 for non-nitro, and <200 for nitro?

**Comment by rajarsheechatterjee** [comment] 2024-03-29 03:14
Closing this issue. The link appears to be working as intended.

**Closed by rajarsheechatterjee** 2024-03-29 03:14 UTC
Labels: Bug
