### ISSUE TITLE
Backup doesn't include progress

### ISSUE THREAD

**Issue by Enix19955** [LNReader/lnreader#860] opened 2023-12-09 18:06 UTC
### Steps to reproduce

.

### Expected behavior

After creating a backup and restoring, the restored novels don't have the reading progress and shows chapter 1 instead of the last read chapter.

### Actual behavior

After creating a backup and restoring, the restored novels don't have the reading progress and shows chapter 1 instead of the last read chapter.

### LNReader version

1.1.18

### Android version

Android 14

### Device

Xiaomi 11T PRO

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.18](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Enix19955** [comment] 2023-12-09 18:10
![Screenshot_2023-12-09-23-37-19-419_com rajarsheechatterjee LNReader](https://github.com/LNReader/lnreader/assets/153387142/3d62bec0-56c7-4cdb-85d6-1f08c94e26ac)
![Screenshot_2023-12-09-23-38-02-254_com rajarsheechatterjee LNReader](https://github.com/LNReader/lnreader/assets/153387142/e41680ac-7206-4f01-8766-6723443580ac)
Above images show the reading progress before creating backup and in the second image there is no reading progress after the restore.

**Comment by rajarsheechatterjee** [comment] 2023-12-29 13:33
Duplicate of #357

Currently the app doesn't support backing up chapter progress.

**Closed by rajarsheechatterjee** 2023-12-29 13:33 UTC
Labels: Bug
