### ISSUE TITLE
Novel Chapter wrong on history tab

### ISSUE THREAD

**Issue by Kai-Nui** [LNReader/lnreader#189] opened 2022-03-03 11:44 UTC
When in history tab, the chapter number with the novel thumbnail does not correspond to the latest read/ currently being read chapter.

**Comment by rajarsheechatterjee** [comment] 2022-03-03 13:45
If it shows -1, that's probably because the chapter name does not contain any number or if it shows a different number that would be because of the chapter name containing multiple numbers.

**Comment by Kai-Nui** [comment] 2022-03-04 14:26
Nah. It seems to be random. Sometimes the chapter number showing is greater than total. And it's not that the labels were mismatched like the source just posted the latter chapters or multiple uploaders from the same source so the numbering is mixed-up. Just weirdly random. It gets fixed sometimes by restarting the device but screws up again out of the blue. Quite odd and confusing. I'm not sure how reproduce the error...

**Comment by rajarsheechatterjee** [comment] 2022-05-08 16:18
Closing since this issue cannot be reproduced. 

Reopen this if you find a way to reproduce it.

**Closed by rajarsheechatterjee** 2022-05-08 16:18 UTC
Labels: Bug, needs more info
