### ISSUE TITLE
Why does Migrate Feature Work

### ISSUE THREAD

**Issue by Pheonix-Flames** [LNReader/lnreader#925] opened 2024-01-29 13:19 UTC
### Steps to reproduce

1. Open a Novel from your Library
2. Click on Migrate option
3. Select the source to migrate 

### Expected behavior

It should Migrate the novel on to the new source and open it in new source 

### Actual behavior

The page stays on the Migration page from where you choose the new source to migrate instead of opening the novel to the new migrated source and there is a Notification in my notification bar that says: Migrating<novel name> and it never goes away until I Force Close the App from App Info in the Settings 

### LNReader version

1.1.19

### Android version

Android 11 

### Device

Realme 3 Pro

### Other details

![Screenshot_2024-01-29-18-47-51-64_e4424258c8b8649f6e67d283a50a2cbc](https://github.com/LNReader/lnreader/assets/105352597/37241ae1-20ec-4cdc-b223-027800b04201)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.19](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment] 2024-02-01 13:38
Duplicate of #864

**Closed by rajarsheechatterjee** 2024-02-01 13:38 UTC
Labels: Bug
