### ISSUE TITLE
Backup Doesn't Save Novel progress

### ISSUE THREAD

**Issue by Pheonix-Flames** [LNReader/lnreader#357] opened 2022-08-09 14:14 UTC
After Restoring Back it doesn't save the progress of the novel it change all the read chapter to Unread

**Comment by nyagami** [comment] 2023-07-02 07:20
done in https://github.com/LNReader/lnreader/pull/659

**Comment by nachfuellbar** [comment] 2023-12-30 16:23
@nyagami is there a timeline when this will be available?
I have 1.1.18 installed and it just includes some metadata about the novel and no progression
The commit seems to be merged in plugins branch but not in main yet (?)
Is there anything blocking this feature from being released?
@rajarsheechatterjee closed a duplicate of this with "not planned"

**Comment by nyagami** [comment] 2023-12-31 02:55
> Is there anything blocking this feature from being released?

It's almost done. But there's no testing.

**Comment by nyagami** [comment] 2024-04-28 14:10
implemented in v2 with self host and Drive backup

**Closed by nyagami** 2024-04-28 14:10 UTC
Labels: Enhancement
