### ISSUE TITLE
Can only search 25 items

### ISSUE THREAD

**Issue by namper77** [LNReader/lnreader#702] opened 2023-07-25 04:23 UTC
### Steps to reproduce

I type imouto in search with novel updates
it only show 25 items and search with other keyword only 25 items

![Screenshot_2023-07-25-11-16-37-75](https://github.com/LNReader/lnreader/assets/96808064/50f3dc6e-0069-4bd3-a868-6f9d253026f9)

### Expected behavior

on novel updates it has 60 or 70 novel

### Actual behavior

Only 25 novel show up
![Screenshot_2023-07-25-11-16-37-75](https://github.com/LNReader/lnreader/assets/96808064/50f3dc6e-0069-4bd3-a868-6f9d253026f9)

### LNReader version

1.1.16

### Android version

Android 12

### Device

Realme q3 pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.16](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment] 2023-07-25 04:57
Duplicate of #502

**Closed by rajarsheechatterjee** 2023-07-25 04:57 UTC
Labels: Bug
