### ISSUE TITLE
Suggested as Risky APP in Phone Manager of Realme RMX3686

### ISSUE THREAD

**Issue by lokesh-kurre** [LNReader/lnreader#819] opened 2023-10-22 09:42 UTC
### Steps to reproduce

1. Install the LNReader v1.1.18 in Realme RMX3686
2. Use the App as usual.
3. After the sometime, the Phone Manager (inbuilt virus scanner) in above device, will report it as Risky App.
    It says, this is rootkit virus which can create hidden file system and hide the malware.

### Expected behavior

App should run as usual, it should not be reported as Risky App.

### Actual behavior

After the using some time, the Phone Manager (inbuilt virus scanner) in above device, will report it as Risky App.
It says, this is rootkit virus which can create hidden file system and hide the malware.

### LNReader version

1.1.18

### Android version

Android 13

### Device

Realme RMX3686

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.18](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment] 2023-10-29 07:46
It's a false positive due to the APK being unsigned.

Duplicate of #724

**Closed by rajarsheechatterjee** 2023-10-29 07:46 UTC
Labels: Bug
