### ISSUE TITLE
continuous TTS When next chapter 

### ISSUE THREAD

**Issue by WGmg23** [LNReader/lnreader#1150] opened 2024-07-18 02:56 UTC
### Describe your suggested feature

If the TTS is active and I move on to the next chapter the TTS continues to work and starts automatically 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/LNReader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[2.0.0](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment] 2024-07-19 06:42
Duplicate of https://github.com/LNReader/lnreader/issues/759

**Closed by rajarsheechatterjee** 2024-07-19 06:42 UTC
Labels: Feature Request
