### ISSUE TITLE
Read from the start feature

### ISSUE THREAD

**Issue by Remielas** [LNReader/lnreader#827] opened 2023-11-01 20:43 UTC
### Describe your suggested feature

It works by making the chapters you read start from the vary start, instead where you left off. 

### Other details

It's very handy for those novels that you forgot to finish reading but is in the middle chapters because even if you unread a chapter, it will still go to the part where you left off

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/LNReader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.18](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Palloxin** [comment] 2023-11-05 16:56
There is already an issue about it #791 and i made a comment that details it in a specific way.

**Comment by rajarsheechatterjee** [comment] 2023-11-11 07:42
Duplicate of #791

**Closed by rajarsheechatterjee** 2023-11-11 07:42 UTC
Labels: Feature Request
