### ISSUE TITLE
Lack of quick response when setting the library on the main interface

### ISSUE THREAD

**Issue by yemenihandsome** [LNReader/lnreader#401] opened 2022-08-20 03:48 UTC
### Steps to reproduce

It does not respond quickly when clicking on the sort settings and does not respond quickly when the settings for displaying chapters in the main interface of the library

### Expected behavior

He must respond quickly when choosing

### Actual behavior

Did not respond quickly when pressing or selecting the option

### LNReader version

1.1.12

### Android version

Android 10

### Device

LG STYLO 5

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.12](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment] 2022-08-20 05:01
Duplicate of #31 

This is similar to the above issue, button interactions in bottom sheet don't work properly on some devices.

**Closed by rajarsheechatterjee** 2022-08-20 05:01 UTC
Labels: Bug
