### ISSUE TITLE
Arabic source kolnovel not work 

### ISSUE THREAD

**Issue by aaee20301** [LNReader/lnreader#1079] opened 2024-05-25 23:08 UTC
### Steps to reproduce

the domain of knovel changed form 
https://kolnovel.com
https://kolnovel.club/

### Expected behavior

 0 00 0

### Actual behavior

the domain kolnovle changed 

### LNReader version

1.1.19

### Android version

android 11

### Device

Samsung a 21

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[2.0.0](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment] 2024-05-28 05:28
> If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).

Duplicate of https://github.com/LNReader/lnreader-plugins/issues/957

**Closed by rajarsheechatterjee** 2024-05-28 05:28 UTC
Labels: Bug
