### ISSUE TITLE
Adding dictionary (custom and online)

### ISSUE THREAD

**Issue by Karutovn** [LNReader/lnreader#1084] opened 2024-05-28 15:52 UTC
### Describe your suggested feature

The dictionary should be added 
- For offline:
   - support kindle dictionary file
   - support lingoes file

For online support 
- English: Cambridge dictionary, oxford dictionary 
- Vietnamese supporting lacviet dict (https://tratu.coviet.vn/hoc-tieng-anh/tu-dien/lac-viet/all/API.html), labandict (https://m.dict.laban.vn/)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/LNReader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[2.0.0](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment] 2024-05-31 04:09
Duplicate of #141

**Closed by rajarsheechatterjee** 2024-05-31 04:09 UTC
Labels: Feature Request
