### ISSUE TITLE
Ability to search words within downloaded chapters

### ISSUE THREAD

**Issue by Palloxin** [LNReader/lnreader#701] opened 2023-07-24 20:58 UTC
### Describe your suggested feature

abiliy to search words within downloaded chapters.

### Why
To recall what chapter a specific thing has been menzioned like the first appearance of a character(or object). Maybe one has a phrase from the novel seen on the web (reddit, discord etc..) and wants to know what chapter it is etc..

example: 
i want to know the chapter where the mc entered a world full gays so i search "cop gay"
![IMG_20230712_210950](https://github.com/LNReader/lnreader/assets/75091899/9e316843-1181-4997-9bcb-cc91bdcb8fb0)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/LNReader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.14](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment] 2023-07-25 03:24
Duplicate of #133

**Closed by rajarsheechatterjee** 2023-07-25 03:24 UTC
Labels: Feature Request
