### ISSUE TITLE
[ Feature Request ] Use local chapter

### ISSUE THREAD

**Issue by JeanTesla1** [LNReader/lnreader#353] opened 2022-08-07 21:24 UTC
Some translator team publish their chapter only on pdf format and don't have website (it's specially the case for french traductor), so having the possibility to import chapter from a local source can be very useful 
(sorry for my broken English)

**Comment by rajarsheechatterjee** [comment] 2022-08-08 13:10
Duplicate of #38

**Closed by rajarsheechatterjee** 2022-08-08 13:10 UTC
