### ISSUE TITLE
[Feature Request] Storage Location

### ISSUE THREAD

**Issue by GAZERUNRIVALED** [LNReader/lnreader#1333] opened 2024-11-19 20:29 UTC
### Describe your suggested feature

![20241120_032635](https://github.com/user-attachments/assets/6551e99b-c8b4-4a75-b805-6cafc3791e16)

### Other details

can you add the above feature

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/LNReader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[2.0.0](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment] 2024-12-24 03:15
Duplicate of #40

**Closed by rajarsheechatterjee** 2024-12-24 03:15 UTC
Labels: Feature Request
