### ISSUE TITLE
Rgb color picker chart in appearance 

### ISSUE THREAD

**Issue by Roaqe** [LNReader/lnreader#523] opened 2023-01-29 17:37 UTC
### Describe your suggested feature

![Screenshot_2023-01-29-23-01-32-74_4d38fce200f96aeac5e860e739312e76](https://user-images.githubusercontent.com/108117429/215344872-7a96a3d7-6b4d-4b24-b3e1-109a87efea65.jpg) A Feature to Directly in appearance category select a color from the chart instead of typing color codes 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/LNReader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.14](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment] 2023-01-29 17:41
Duplicate of #463

**Closed by rajarsheechatterjee** 2023-01-29 17:41 UTC
Labels: Feature Request
