### ISSUE TITLE
Add refresh button to Network Request Failed page

### ISSUE THREAD

**Issue by Palloxin** [LNReader/lnreader#842] opened 2023-11-11 10:15 UTC
### Describe your suggested feature

![IMG_20231111_110434](https://github.com/LNReader/lnreader/assets/75091899/23366908-9ac6-44c6-ad5d-3364d1234e69)

Add a refresh button.

### Other details

It is a QoL change.
Very similar to the issue #667 
There might be other similar pages that requure the refresh button like the cloudflare one.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/LNReader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.18](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment] 2023-11-11 10:19
Duplicate of #667

**Closed by rajarsheechatterjee** 2023-11-11 10:19 UTC
Labels: Feature Request

**Comment by Palloxin** [comment] 2023-11-11 10:22
It is similar, the difference is that rhis is is about the page that appear if u have no internet. The issue 667 is about cloudflare blocking error. Can this issue be reopened?

**Comment by rajarsheechatterjee** [comment] 2023-11-11 10:24
No, it's the same screen with a different error message. Fixing one should fix all other cases.
