### ISSUE TITLE
"Render HTML" option while reading cannot be enabled on Samsung, Navigation buttons blocking.

### ISSUE THREAD

**Issue by YeetingWaterbottle** [LNReader/lnreader#230] opened 2022-04-13 23:43 UTC
The buttons for navigation on Samsung is blocking on toggle for "Render HTML" and cannot clicked until you set your device to landscape mode. Scrolling through the setting while reading is also buggy, sometimes it scrolls and sometimes doesn't.

![image](https://user-images.githubusercontent.com/73762047/163287190-f60a8370-6353-46ea-88db-c93eec63de18.png)

**Comment by rajarsheechatterjee** [comment] 2022-04-14 13:52
Buttons/touch interactions in bottom sheets not working properly is a Samsung specific issue, they work fine on other devices. I can't reproduce or fix this as I don't have a Samsung device.

**Comment by YeetingWaterbottle** [comment] 2022-04-14 14:24
> Buttons/touch interactions in bottom sheets not working properly is a Samsung specific issue, they work fine on other devices. I can't reproduce or fix this as I don't have a Samsung device. 

I see, is the scrolling problem also Samsung specific?

**Comment by rajarsheechatterjee** [comment] 2022-04-16 16:16
> I see, is the scrolling problem also Samsung specific?

Probably since it works fine on my device.

**Comment by XaaRii** [comment] 2022-05-03 20:51
> The buttons for navigation on Samsung is blocking on toggle for "Render HTML" and cannot clicked until you set your device to landscape mode. Scrolling through the setting while reading is also buggy, sometimes it scrolls and sometimes doesn't.

I didn't remember anything weird / unresponsible when i first went through the settings, so at first i thought it's just a specific model bug thing, but just out of curiosity i checked it anyways. How couldn't i notice it? i have no clue.

Regarding the "menu rendering under navigation panel" issue, you can just scroll through the menu to get to the button. I also double-checked that if you scroll to the bottom, there is no obstructed selection left -> everything is accessible, thus no problem here.

Regarding the "scrolling" issue, it seems like the LNReader thinks you want to slide **with** the settings window instead of scrolling **inside** of it. I have no idea who thought being able to slide with settings panel was a good idea. Anyways, I would recommend either [making sure settings panel can be closed via swiping **only** if you are scrolled on the top] or [limiting the ability to move with setting panel only to the borders of it]

if you didn't understand what i said/what the problem is, i can make a screen recording showcasing it.

...damn, that was longer than i planned it to be, sorry

**Closed** 2022-05-07 08:07 UTC
