### ISSUE TITLE
Contain malware PUP/Android.Malct.

### ISSUE THREAD

**Issue by ChandanKSDeveloper** [LNReader/lnreader#1000] opened 2024-03-12 16:45 UTC
### Steps to reproduce

Contain PUP/Android.Malct.518314 malware when scanned on virustotal. 
![Screenshot_2024-03-12-21-42-13-84_e4424258c8b8649f6e67d283a50a2cbc](https://github.com/LNReader/lnreader/assets/134827026/6ed57ee8-13c0-4789-a650-24f148ccf437)

### Expected behavior

Remove this malware 

### Actual behavior

Remove this malware . Since it contains PUP/Android.Malct.518314 . My antivirus suggesting me to remove this apk

### LNReader version

1.1.19

### Android version

Android 12

### Device

Realme x7

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.19](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment] 2024-03-13 13:32
It's a false positive due to the APK being unsigned.

Duplicate of https://github.com/LNReader/lnreader/discussions/724

**Closed** 2024-03-13 13:32 UTC
Labels: Bug
