### ISSUE TITLE
Download Novels To The SD Card

### ISSUE THREAD

**Issue by tehchy123** [LNReader/lnreader#451] opened 2022-10-20 10:43 UTC
### Describe your suggested feature

In the settings page (maybe downloads), please have an option to choose between downloading novels to the SD card or internal storage for off-line viewing. This will help us people who have an older phone WITH an SD card slot

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/LNReader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.13](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment] 2022-11-13 15:32
Duplicate of #40

**Closed by rajarsheechatterjee** 2022-11-13 15:32 UTC
Labels: Feature Request
