### ISSUE TITLE
Vanishing Bottom Navigation tabs

### ISSUE THREAD

**Issue by piratelord69** [LNReader/lnreader#1297] opened 2024-10-30 17:16 UTC
### Steps to reproduce

1. Open the app.
2.  Open any book in category
3.  Select continue reading.
4.  The bottom navigation bar which shows options like Library, Updates, History vanishes after returning to library screen.

### Expected behavior

The bottom navigation bar should be present.

### Actual behavior

The bottom navigation bar is absent.

### LNReader version

1.1.19

### Android version

Android 15

### Device

Google pixel 8

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [ ] I have updated the app to version **[2.0.0](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by piratelord69** [comment] 2024-10-30 17:18
I'm not updating to 2.0 as I'm waiting for stable release, and the issue fixes itself when the app is restarted

**Comment by rajarsheechatterjee** [comment] 2024-11-04 17:21
I am unable to reproduce this in v2.0.0 beta. Significant changes have been made since v1.1.19, and the next stable update will be based on v2.0.0. Closing this.

**Closed by rajarsheechatterjee** 2024-11-04 17:21 UTC
Labels: Bug
