### ISSUE TITLE
Custom  font

### ISSUE THREAD

**Issue by ghost** [LNReader/lnreader#849] opened 2023-11-17 20:37 UTC
### Describe your suggested feature

Add custom font from Mobile option

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/LNReader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.18](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment] 2023-11-18 02:09
Duplicate of #736

**Closed by rajarsheechatterjee** 2023-11-18 02:09 UTC
Labels: Feature Request
