### ISSUE TITLE
Start screen reader mid-chapter.

### ISSUE THREAD

**Issue by JohnathonStampe** [LNReader/lnreader#577] opened 2023-03-13 00:00 UTC
### Describe your suggested feature

The user can select text, so add an option to "Start TTS from here" when the selection menu is shown.

### Other details

My app crashes fequently. It a big ask for someone to debug it, but with this feature I can find my spot and start up TTS again. Its great for stories with LONG chapters, since listening to the first part may be 10 minutes.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/LNReader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.14](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment] 2023-03-14 00:58
Duplicate of #90

> My app crashes fequently. It a big ask for someone to debug it, but with this feature I can find my spot and start up TTS again. Its great for stories with LONG chapters, since listening to the first part may be 10 minutes.

Crashes related to TTS should be fixed in develop, you can try the latest preview from [here](https://github.com/LNReader/lnreader-preview/releases/tag/v1.1.14.1).

**Closed by rajarsheechatterjee** 2023-03-14 00:58 UTC
Labels: Feature Request
