### ISSUE TITLE
Novel Downloading

### ISSUE THREAD

**Issue by MonomoySama** [LNReader/lnreader#812] opened 2023-10-15 05:25 UTC
### Describe your suggested feature

It'd be nice to have the feature to download 4/5 chapters of a novel at once instead of 1 after 1. It takes more time that ways

### Other details

Let's say i put 100 chaps on download together. It takes too much time with "1 after another" download setting

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/LNReader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.18](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment] 2023-10-15 05:55
Duplicate of #471

**Closed by rajarsheechatterjee** 2023-10-15 05:55 UTC
Labels: Feature Request
