### ISSUE TITLE
Novelupdates not working as intended

### ISSUE THREAD

**Issue by maosama600** [LNReader/lnreader#988] opened 2024-03-05 19:12 UTC
### Steps to reproduce

First step
When updating said novel to get new added chapters.(how it starred)
Now even added novels have chapters the do not belong to them but other random novels instead.

### Expected behavior

It should add the chapters that where added in novelupdates

### Actual behavior

Example of updated novel
![Screenshot_2024-03-05-20-05-15-81](https://github.com/LNReader/lnreader/assets/61079118/ca6c024e-6c63-4e19-9bfc-e7fc1a00125b)
![Screenshot_2024-03-05-20-05-25-02](https://github.com/LNReader/lnreader/assets/61079118/b0f36fc7-66e1-4379-8b0f-5c1de4767d28)

What should be displayed 
![Screenshot_2024-03-05-20-06-02-14](https://github.com/LNReader/lnreader/assets/61079118/7c387f7b-e0e4-4231-967f-ec9e4436965d)

New novel
![Screenshot_2024-03-05-20-09-10-47](https://github.com/LNReader/lnreader/assets/61079118/f3882df1-4ae5-4ceb-a950-064b4c10a066)
Reading chapters through the app (not the correct chapter)
![Uploading Screenshot_2024-03-05-20-09-23-20.png…]()
Using the link in novelupdates website
![Uploading Screenshot_2024-03-05-20-10-19-17.png…]()

### LNReader version

1.1.19

### Android version

8.1.0

### Device

Oppo a7

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.19](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment] 2024-03-06 04:06
> If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).

Duplicate of https://github.com/LNReader/lnreader-sources/issues/736

**Closed by rajarsheechatterjee** 2024-03-06 04:06 UTC
Labels: Bug
