### ISSUE TITLE
Audio

### ISSUE THREAD

**Issue by Magicstar7** [LNReader/lnreader#349] opened 2022-08-02 11:14 UTC
When starting audio reading it takes a minute to get started. If you pause the audio reading you have to start from the beginning of the chapter.

You can close the app when you audio is on, but audio stops if you go out of the chapter in the app. 

And you can't pause the audio outside the app.
(it would be nice to have somthing like Spotify outside of the app)

It would also be nice to have more options on voices on the audio reader.

**Comment by Magicstar7** [comment] 2022-08-03 00:13
The audio reder also stops for a minute 1 or 2 timse half way through every chapters.

**Comment by rajarsheechatterjee** [comment] 2022-08-05 15:57
The [package](https://github.com/ak1394/react-native-tts) which I use for TTS doesn't support those features so it's not possible to implement them right now.

Duplicate of #90

**Closed by rajarsheechatterjee** 2022-08-05 15:57 UTC
