### ISSUE TITLE
Bug & Feature Request

### ISSUE THREAD

**Issue by jingoniii** [LNReader/lnreader#232] opened 2022-04-19 07:04 UTC
The swipe gesture while reading sometimes does not work properly to the point I need to swipe it multiple times to proceed on the next chapter. Thus, I currently used the "›" button right now because the swipe gesture is a hassle to me. I also want to request feature in this app like infinite scroll because I believe it is more convenient to me, and used by most reading application out there. The sources are also limited in this application when I tried to search a light novel from Japan, it gave me nothing so I find other alternative application to this just to read those light novel that are not present in this application. All in all, this is a good application. Good job to dev!

**Comment by rajarsheechatterjee** [comment] 2022-04-22 14:44
Already requested.

Duplicate of #43 
Duplicate of #112

**Closed by rajarsheechatterjee** 2022-04-22 14:44 UTC
