### ISSUE TITLE
Turn page when TTS is done with the chapter

### ISSUE THREAD

**Issue by Vitoko99** [LNReader/lnreader#759] opened 2023-08-24 09:51 UTC
### Describe your suggested feature

I would love a feature that lets the app turn to the next page wjen the tts is done reading the chapter because that way we don't need to pick up the phone every time the chapter is done.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/LNReader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.14](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Palloxin** [comment] 2024-08-20 13:26
Duplicate of #465

**Closed** 2024-08-21 03:25 UTC
Labels: Feature Request
