### ISSUE TITLE
Adding traditional Chinese in linovelib source

### ISSUE THREAD

**Issue by waijaii** [LNReader/lnreader#1078] opened 2024-05-25 11:32 UTC
### Describe your suggested feature

I think adding traditional Chinese version of linovelib would be better for traditional Chinese reader. Currently only simplified Chinese is supported with (https://www.bilinovel.com/). Traditional Chinese is supported in the same website (https://tw.linovelib.com/) , by the ‘繁體’ button at the lowest in the https://www.bilinovel.com/.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/LNReader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[2.0.0](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment] 2024-05-28 05:54
Duplicate of https://github.com/LNReader/lnreader-plugins/issues/744

**Closed by rajarsheechatterjee** 2024-05-28 05:54 UTC
Labels: Feature Request
